### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mixmastamyk** [onecodex/chrononaut#2]
Impressive work, thanks.

Wondering what the future will bring to this extension?  Will there be new features, bug fixes, support, maintenance, etc?

**Comment by boydgreenfield** [comment]
@mixmastamyk Thanks! We use this in production (and plan to bring it to a few other micro-services), so do expect to continue to provide bug fixes and support. We are using Postgres exclusively, so that's the focus for the time being there.

Regarding new features, I would also like to slowly expand the API with the ability to query models at a specific point in time (a `with rewind(date)` context manager or similar...), query versioned attributes, etc. I also expect there are some issues under higher load related to, e.g., DB flushes that we'll probably add as we encounter those in our use cases.

Helpful? Happy to take suggestions!

**Comment by boydgreenfield** [comment]
Closing this as we've shared a bit of roadmap and are landing some new features. But please feel free to open new issues with any requests @mixmastamyk!

**Comment by mixmastamyk** [comment]
Thanks.  ;)
